name: Load_Test_8000

on:
  workflow_run:
    workflows: [Load_Test_5000]
    branches: [main test-workflow-dependency]
    
    types:
      - completed
      - requested




jobs:
  on-success:
    name: Load test
    runs-on:  [self-hosted, kubernetes,extra-resources]

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Setup Java JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

#     - name: Check out code
#       uses: actions/checkout@v2

#     - name: jmeter
#       run: |
#         bash loadTests/test.sh . universal-example-test-plan.jmx dev  krogo-universal-example-central.appfmk-dev.kpsazc.dgtl.kroger.com 8000
#     - name: Publish JMeter Report
#       uses: actions/upload-artifact@v2
#       with:
#         name: load-test-report-artifact
#         path: report
